name = "telegram-furancho-orquestador"
main = "src/worker.js"
compatibility_date = "2024-08-29"

[durable_objects]
bindings = [ { name = "STATE_MANAGER", class_name = "StateManager" } ]

[[migrations]]
tag = "v1"
new_classes = ["StateManager"]

[vars]
AGENT1_URL = "https://telegram-furancho-agente-1.sociobot.workers.dev"
AGENT2_URL = "https://telegram-furancho-agente-2.sociobot.workers.dev"
