name = "telegram-furancho-orquestador"
main = "src/worker.js"
compatibility_date = "2024-08-29"

[[kv_namespaces]]
binding = "AGENTS_KV"
id = "107bf9e3db69499f9f8d61d733fd435d" # <-- El ID de tu KV

[vars]
AGENT1_URL = "https://telegram-furancho-agente-1.sociobot.workers.dev"
AGENT2_URL = "https://telegram-furancho-agente-2.sociobot.workers.dev"
# Forzando un redespliegue el 1 de Septiembre
